name: Build and Deploy
env:
   OUTPUT_PATH: ${{ github.workspace }}/.output
   DOTNET_VERSION: "3.1"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@main

      - name: Setup Dotnet ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Publish functions
        run: dotnet publish --configuration Release --output ${{ env.OUTPUT_PATH }}
        working-directory: ./AzFunction
      - name: Package functions
        uses: actions/upload-artifact@v1
        with:
          name: functions
          path: ${{ env.OUTPUT_PATH }}

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    env:
      FUNC_APP_NAME: function-app-uc1
    steps:
      - uses: azure/login@v1
        with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Download website
        uses: actions/download-artifact@v1
        with:
          name: functions
          path: ${{ env.OUTPUT_PATH }}
     
      - name: "Run Azure Functions Action"
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.FUNC_APP_NAME }}
          package: ${{ env.OUTPUT_PATH }}
          publish-profile: ${{ secrets.SCM_CREDENTIALS }}
